FROM apache/airflow:latest

COPY requirements.txt /requirements.txt

USER root

RUN mkdir -p /data && chmod 777 /data

USER airflow

RUN python -m pip install --upgrade pip && \
    pip install --no-cache-dir -r /requirements.txt
